### ISSUE TITLE
Issue in Enable Persistece in Spring boot Project

### ISSUE THREAD

**Issue by duke-nuke** [phax/phase4#53]
I am trying to enable persistent by setting the property 
phase4.manager.inmemory=false and 
global.datapath=phase4-data
but the AS4 server is not starting up due to the following stack-trace 

```
2021-05-23 15:13:26.406  INFO 23404 --- [  restartedMain] c.h.p.s.Phase4SpringbootApplication      : Starting Phase4SpringbootApplication on DESKTOP-CDB8RFB with PID 23404 (F:\work\xi\as4-server\target\classes started by khurram in F:\work\xi)
2021-05-23 15:13:26.410  INFO 23404 --- [  restartedMain] c.h.p.s.Phase4SpringbootApplication      : No active profile set, falling back to default profiles: default
2021-05-23 15:13:26.510  INFO 23404 --- [  restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in C:\Users\khurram\.m2\repository\com\sun\xml\bind\jaxb-impl\3.0.0\jaxb-impl-3.0.0.jar referenced one or more files that do not exist: file:/C:/Users/khurram/.m2/repository/com/sun/xml/bind/jaxb-impl/3.0.0/jaxb-core.jar
2021-05-23 15:13:26.510  INFO 23404 --- [  restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in C:\Users\khurram\.m2\repository\org\glassfish\jaxb\jaxb-core\2.2.11\jaxb-core-2.2.11.jar referenced one or more files that do not exist: file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-core/2.2.11/jaxb-api-2.2.12-b140109.1041.jar,file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-core/2.2.11/txw2-2.2.11.jar,file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-core/2.2.11/istack-commons-runtime-2.21.jar
2021-05-23 15:13:26.510  INFO 23404 --- [  restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in C:\Users\khurram\.m2\repository\org\glassfish\jaxb\jaxb-runtime\2.3.1\jaxb-runtime-2.3.1.jar referenced one or more files that do not exist: file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/jaxb-api-2.3.1.jar,file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/txw2-2.3.1.jar,file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/istack-commons-runtime-3.0.7.jar,file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/stax-ex-1.8.jar,file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/FastInfoset-1.2.15.jar,file:/C:/Users/khurram/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/javax.activation-api-1.2.0.jar
2021-05-23 15:13:26.510  INFO 23404 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-05-23 15:13:26.510  INFO 23404 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-05-23 15:13:27.205  INFO 23404 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-05-23 15:13:27.309  INFO 23404 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 95ms. Found 9 JPA repository interfaces.
2021-05-23 15:13:28.507  INFO 23404 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9091 (http)
2021-05-23 15:13:28.516  INFO 23404 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-05-23 15:13:28.516  INFO 23404 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.37]
2021-05-23 15:13:28.663  INFO 23404 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-05-23 15:13:28.664  INFO 23404 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2153 ms
2021-05-23 15:13:28.752  INFO 23404 --- [  restartedMain] c.h.x.requesttrack.RequestTracker        : RequestTrackerMonitor was installed successfully.
2021-05-23 15:13:28.861  WARN 23404 --- [  restartedMain] c.h.c.e.EqualsImplementationRegistry     : Another equals implementation for class class javax.xml.bind.JAXBElement is already registered (com.helger.jaxb.adapter.config.JAXBEqualsImplementationRegistrarSPI$$Lambda$543/273220887@68158835) so it is not overwritten with com.helger.jaxb.config.JAXBEqualsImplementationRegistrarSPI$$Lambda$571/2103413172@6c050b9c
2021-05-23 15:13:28.879  INFO 23404 --- [  restartedMain] com.helger.phase4.mgr.MetaAS4Manager     : MetaAS4Manager is initialized using file system persistence
2021-05-23 15:13:28.882  INFO 23404 --- [  restartedMain] com.helger.phase4.mgr.MetaAS4Manager     : Creating AS4 managers using factory class com.helger.phase4.mgr.ManagerFactoryPersistingFileSystem
2021-05-23 15:13:28.900 ERROR 23404 --- [  restartedMain] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletRegistrationBean' defined in com.helger.phase4.springboot.servlet.ServletConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is com.helger.commons.exception.InitializationException: Failed to init MetaAS4Manager
2021-05-23 15:13:28.920  INFO 23404 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-05-23 15:13:28.927  WARN 23404 --- [  restartedMain] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [RequestTrackerMonitor-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
2021-05-23 15:13:28.928  WARN 23404 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2021-05-23 15:13:28.935  WARN 23404 --- [  restartedMain] c.h.scope.singleton.AbstractSingleton    : Object not instantiated is destroyed soon: [MetaAS4Manager@0x060e0d6a: Status={}]
2021-05-23 15:13:28.935  INFO 23404 --- [  restartedMain] c.h.x.requesttrack.RequestTracker        : RequestTrackerMonitor is now shutting down
2021-05-23 15:13:28.936  INFO 23404 --- [  restartedMain] c.h.x.requesttrack.RequestTracker        : RequestTrackerMonitor was uninstalled successfully.
2021-05-23 15:13:28.937  WARN 23404 --- [  restartedMain] c.h.scope.singleton.AbstractSingleton    : Object not instantiated is now destroyed: [MetaAS4Manager@0x060e0d6a: Status={2}]
2021-05-23 15:13:28.948  INFO 23404 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-23 15:13:28.956 ERROR 23404 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at com.helger.phase4.springboot.Phase4SpringbootApplication.main(Phase4SpringbootApplication.java:49) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.3.2.RELEASE.jar:2.3.2.RELEASE]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:142) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:437) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:191) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	... 14 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletRegistrationBean' defined in com.helger.phase4.springboot.servlet.ServletConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is com.helger.commons.exception.InitializationException: Failed to init MetaAS4Manager
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:211) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:202) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:96) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:85) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:255) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:229) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5128) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_251]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:1.8.0_251]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_251]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:1.8.0_251]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is com.helger.commons.exception.InitializationException: Failed to init MetaAS4Manager
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 61 common frames omitted
Caused by: com.helger.commons.exception.InitializationException: Failed to init MetaAS4Manager
	at com.helger.phase4.mgr.MetaAS4Manager.onAfterInstantiation(MetaAS4Manager.java:117) ~[phase4-lib-1.3.0.jar:1.3.0]
	at com.helger.scope.singleton.AbstractSingleton.getSingleton(AbstractSingleton.java:560) ~[ph-scopes-10.1.1.jar:10.1.1]
	at com.helger.scope.singleton.AbstractGlobalSingleton.getGlobalSingleton(AbstractGlobalSingleton.java:65) ~[ph-scopes-10.1.1.jar:10.1.1]
	at com.helger.phase4.mgr.MetaAS4Manager.getInstance(MetaAS4Manager.java:124) ~[phase4-lib-1.3.0.jar:1.3.0]
	at com.helger.phase4.servlet.AS4ServerInitializer.initAS4Server(AS4ServerInitializer.java:60) ~[phase4-lib-1.3.0.jar:1.3.0]
	at com.helger.phase4.springboot.servlet.ServletConfig._initAS4(ServletConfig.java:104) ~[classes/:na]
	at com.helger.phase4.springboot.servlet.ServletConfig._init(ServletConfig.java:76) ~[classes/:na]
	at com.helger.phase4.springboot.servlet.ServletConfig.servletRegistrationBean(ServletConfig.java:63) ~[classes/:na]
	at com.helger.phase4.springboot.servlet.ServletConfig$$EnhancerBySpringCGLIB$$954d33f9.CGLIB$servletRegistrationBean$1(<generated>) ~[classes/:na]
	at com.helger.phase4.springboot.servlet.ServletConfig$$EnhancerBySpringCGLIB$$954d33f9$$FastClassBySpringCGLIB$$282ebb10.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.helger.phase4.springboot.servlet.ServletConfig$$EnhancerBySpringCGLIB$$954d33f9.servletRegistrationBean(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 62 common frames omitted
Caused by: java.lang.IllegalStateException: Data path was not initialized!
	at com.helger.photon.app.io.WebFileIO.getDataIO(WebFileIO.java:140) ~[ph-oton-app-8.3.0.jar:8.3.0]
	at com.helger.photon.app.dao.AbstractPhotonMapBasedWALDAO.<init>(AbstractPhotonMapBasedWALDAO.java:51) ~[ph-oton-app-8.3.0.jar:8.3.0]
	at com.helger.photon.app.dao.AbstractPhotonMapBasedWALDAO.<init>(AbstractPhotonMapBasedWALDAO.java:44) ~[ph-oton-app-8.3.0.jar:8.3.0]
	at com.helger.phase4.model.mpc.MPCManager.<init>(MPCManager.java:41) ~[phase4-lib-1.3.0.jar:1.3.0]
	at com.helger.phase4.mgr.ManagerFactoryPersistingFileSystem.createMPCManager(ManagerFactoryPersistingFileSystem.java:50) ~[phase4-lib-1.3.0.jar:1.3.0]
	at com.helger.phase4.mgr.MetaAS4Manager.onAfterInstantiation(MetaAS4Manager.java:105) ~[phase4-lib-1.3.0.jar:1.3.0]
	... 79 common frames omitted
```

**Comment by phax** [comment]
To init the data path, you need to call
```java
WebFileIO.initPaths (File aDataPath, String sServletContextPath, boolean bFileAccessCheck);
```
This is currently not done in `ServletConfig` and that's why the configuration entry is useless ;-)
But thanks for pointing it out - I added the initialization stuff in the commit https://github.com/phax/phase4/commit/2380eef8cffd02baffaaea400fd67561a17d60d7 so you can apply this to your local setup if you like.

hth

**Comment by phax** [comment]
Closing this for now. Seems to have done the job
