### ISSUE TITLE
getting 'Context Initialization Error' when trying to run 'JettyStopPHASE4PEPPOL' 

### ISSUE THREAD

**Issue by chamikaCN** [phax/phase4#84]
I tried to setup the Jetty server as instructed in the [wiki pages](https://github.com/phax/phase4/wiki/Testing). Attempted this `Start the server locally, by running the Java application src/test/java/com.helger.phase4.peppol.server.standalone.RunInJettyPHASE4PEPPOL `step but I am getting an error. The stack trace indicates `Failed to determine real path of ServletContext ServletContext`. Any idea why I'm facing this issue? (I am kind of new to the domain).

`[phase4-peppol] [ERROR] [main] Context Initialization Error -- com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:747)
java.lang.IllegalStateException: Failed to determine real path of ServletContext ServletContext@o.e.j.w.WebAppContext@77128536{/,file:///home/<>/phase4/target/webapp-classes,STARTING}
	at com.helger.servlet.ServletHelper.getServletContextBasePath(ServletHelper.java:440) ~[ph-servlet-9.6.4.jar:9.6.4]
	at com.helger.photon.core.servlet.WebAppListener.getServletContextPath(WebAppListener.java:412) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at com.helger.photon.core.servlet.WebAppListener.initPaths(WebAppListener.java:484) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:691) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1073) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:1002) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.Server.start(Server.java:423) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.Server.doStart(Server.java:387) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at com.helger.photon.jetty.JettyStarter.run(JettyStarter.java:725) ~[ph-oton-jetty-8.4.0.jar:8.4.0]
	at com.helger.phase4.peppol.server.standalone.RunInJettyPHASE4PEPPOL.main(RunInJettyPHASE4PEPPOL.java:32) ~[test-classes/:?]
[2022-05-23T15:49:07,892] [phase4-peppol] [WARN ] [main] Failed startup of context o.e.j.w.WebAppContext@77128536{/,file:///home/<>/phase4/target/webapp-classes,UNAVAILABLE} -- org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:533)
java.lang.IllegalStateException: Failed to determine real path of ServletContext ServletContext@o.e.j.w.WebAppContext@77128536{/,file:///home/chamika/Work/phase4/target/webapp-classes,STARTING}
	at com.helger.servlet.ServletHelper.getServletContextBasePath(ServletHelper.java:440) ~[ph-servlet-9.6.4.jar:9.6.4]
	at com.helger.photon.core.servlet.WebAppListener.getServletContextPath(WebAppListener.java:412) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at com.helger.photon.core.servlet.WebAppListener.initPaths(WebAppListener.java:484) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:691) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1073) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:1002) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.Server.start(Server.java:423) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.Server.doStart(Server.java:387) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at com.helger.photon.jetty.JettyStarter.run(JettyStarter.java:725) ~[ph-oton-jetty-8.4.0.jar:8.4.0]
	at com.helger.phase4.peppol.server.standalone.RunInJettyPHASE4PEPPOL.main(RunInJettyPHASE4PEPPOL.java:32) ~[test-classes/:?]
[2022-05-23T15:49:07,892] [phase4-peppol] [INFO ] [main] node0 Stopped scavenging -- org.eclipse.jetty.server.session.HouseKeeper.stopScavenging(HouseKeeper.java:149)
[2022-05-23T15:49:07,894] [phase4-peppol] [ERROR] [main] Failed to start Jetty RunInJettyPHASE4PEPPOL! -- com.helger.photon.jetty.JettyStarter.run(JettyStarter.java:752)
java.lang.IllegalStateException: Failed to determine real path of ServletContext ServletContext@o.e.j.w.WebAppContext@77128536{/,file:///home/<>/phase4/target/webapp-classes,STARTING}
	at com.helger.servlet.ServletHelper.getServletContextBasePath(ServletHelper.java:440) ~[ph-servlet-9.6.4.jar:9.6.4]
	at com.helger.photon.core.servlet.WebAppListener.getServletContextPath(WebAppListener.java:412) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at com.helger.photon.core.servlet.WebAppListener.initPaths(WebAppListener.java:484) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:691) ~[ph-oton-core-8.4.0.jar:8.4.0]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1073) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:1002) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) ~[jetty-webapp-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.Server.start(Server.java:423) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.server.Server.doStart(Server.java:387) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
	at com.helger.photon.jetty.JettyStarter.run(JettyStarter.java:725) ~[ph-oton-jetty-8.4.0.jar:8.4.0]
	at com.helger.phase4.peppol.server.standalone.RunInJettyPHASE4PEPPOL.main(RunInJettyPHASE4PEPPOL.java:32) ~[test-classes/:?]`

**Comment by chamikaCN** [comment]
Hi,
There are 2 levels of **pom.xml**s  in the repo.  I have attached a screenshot as per your request.
- Main pom.xml file in the outer directory (2 in SS)
- separate pom.xml files in each nested module ( 1 in SS)
which one of these two should be in the base directory?

**Comment by phax** [comment]
I think it should be folder Nr. 1.
If I am not mistaken, the default in IntelliJ is "Src"

**Comment by chamikaCN** [comment]
Thanks phillip, got the server up and running with some tweaks. 

I have another small issue to clarify. when setting up the client you have instructed to change the `certificate used in the builders receiverEndpointDetails method`. Where exactly should I include my certificate public key in order to fix the 'Peppol send result: AS4_ERROR_MESSAGE_RECEIVED` issue?

**Comment by phax** [comment]
Okay super :)
When you receive an AS4 error message, you should look into it, and see what the error is. I may be a certificate error, but it may also be something else. If you don't get it from the dumps, you can install an `signalMsgConsumer` in the builder that delivers you the AS4 Signal Message for evaluation.

Well, if you are using Peppol, you are receiving the certificate of the receiver from the "SMP". So if your client builder contains a "smpClient" field, it should do the trick. With the builder methods `certificateConsumer` and `endpointURLConsumer` you can install callbacks that give you the obtained details for the two fields.

hth, Philip

**Comment by chamikaCN** [comment]
Got it done Philip, thanks for the advice. :)
